### ISSUE TITLE
Issue when using include command before cmd_loop

### ISSUE THREAD

**Issue by Sidneys1** [ameily/pypsi#33]
A bug was introduced in #30:

`shell.running` is not instantiated in `shell.__init__`, causing `'Shell' object has no attribute 'running'` if the `include` command is used before `cmd_loop` is called.
